### PR TITLE
Remove leftover indentation text nodes in DOM when elements are removed

### LINKED ISSUE #129: Maven.writeModel breaks some tests since v31
Hey,

Since `v31` my tests are broken. I use `Maven.writeModel`.

image

(left: `v34`; right: `v30`)
There is a new line added (l33 since `v31`). Do you think that it is normal?

Thanks

### PR DESCRIPTION
**Pull request by gastaldi**
- Fixes #129

### CODE REVIEW

**Comment by gastaldi** [comment]
@qmonmert [`b21fb24` (#130)](https://github.com/fabric8-launcher/maven-model-helper/pull/130/commits/b21fb24e041beecf0ea64e2d1d186f54cef4820f) looks like it doesn't mess up the final content

**Comment by gastaldi** [comment]
@qmonmert @murdos I believe I have fixed the issue you reported with this PR. Can any of you please give it a try and let me know?

**Review by qmonmert — APPROVED** [review]

**Comment by qmonmert** [comment]
can you publish a beta version to test in our project?

**Comment by murdos** [comment]
@qmonmert : I'll build a snapshot version locally and test it.

**Comment by murdos** [comment]
@gastaldi : it's a bit better, but there's still an extra line:
```xml
 <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
      <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-dependencies</artifactId>
        <version>${spring-boot.version}</version>
        <scope>import</scope>
        
      </dependency>
    </dependencies>
  </dependencyManagement>
```

**Comment by gastaldi** [comment]
@murdos @qmonmert I added your test and a potential fix now, can you have another look, please?

**Comment by murdos** [comment]
@gastaldi : the issue mentioned above https://github.com/fabric8-launcher/maven-model-helper/pull/130#issuecomment-2013679208 is still present :/
I'll try to reproduce and provide a minimalist test case.

**Comment by murdos** [comment]
> @gastaldi : the issue mentioned above [#130 (comment)](https://github.com/fabric8-launcher/maven-model-helper/pull/130#issuecomment-2013679208) is still present :/ I'll try to reproduce and provide a minimalist test case.

@gastaldi : Here's the test modified to reproduce the issue:
```java
    @Test
    void should_not_add_extra_line_break() throws Exception {
        Path pom = Paths.get(getClass().getResource("extra-line-pom.xml").toURI());
        Model model = Maven.readModel(pom);
        model.getDependencyManagement().getDependencies().remove(0);
        Dependency dep = new Dependency();
        dep.setGroupId("org.springframework.boot");
        dep.setArtifactId("spring-boot-dependencies");
        dep.setVersion("${spring-boot.version}");
        dep.setScope("import");
        dep.setType("pom");
        Dependency dep2 = new Dependency();
        dep2.setGroupId("org.springframework.boot");
        dep2.setArtifactId("spring-boot-dependencies");
        dep2.setVersion("${spring-boot.version}");
        dep2.setScope("import");
        model.getDependencyManagement().addDependency(dep2);
        StringWriter sw = new StringWriter();
        Maven.writeModel(model, sw);
        Approvals.verify(sw.toString());
    }
```

**Comment by gastaldi** [comment]
@murdos thank you for the test case, I've pushed a potential fix again, can you give it a try?

**Comment by murdos** [comment]
@gastaldi : I just tried, and it's now fixed! Thanks :-)

**Comment by gastaldi** [comment]
@murdos @qmonmert thank you very much for reporting and providing the test case. 35 should be on its way to central now, enjoy!

**Comment by qmonmert** [comment]
@gastaldi thanks to you 🙂

**Pull request merged**
